[package]
name = "kd-server"
version = "0.1.0"
edition = "2024"

[dependencies]
kd-shared.path = "../kd-shared"
anyhow.workspace = true
serde.workspace = true
eframe = {version = "0.34.2", features = ["persistence", "ron", "serde"]}
egui = "0.34.2"
image = "0.25.10"
qrcode = "0.14.1"
rfd = "0.17.2"
toml = "1.1.2+spec-1.1.0"
uuid.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
ffmpeg-next = { version = "8.1.0", default-features = false, features = [
    "codec",
    "format",
    "software-scaling"
]}
windows = { version = "0.62.2", features = [
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi"
]}

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-core-media = "0.3"
objc2-core-video = "0.3"
objc2-av-foundation = "0.3"
objc2-screen-capture-kit = "0.3"
block2 = "0.6"
