[package]
name = "kd-server"
version = "0.1.0"
edition = "2024"

[dependencies]
kd-shared.path = "../kd-shared"
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
axum = "0.8.9"
eframe = {version = "0.35.0", features = ["persistence", "ron", "serde"]}
egui = "0.35.0"
http = "1.4.2"
image = "0.25.10"
qrcode = "0.14.1"
rfd = "0.17.2"
toml = "1.1.2+spec-1.1.0"
uuid.workspace = true
crossbeam-channel = "0.5.15"

[target.'cfg(target_os = "windows")'.dependencies]
ffmpeg-next = { version = "8.1.0", default-features = false, features = [
    "codec",
    "format",
    "software-scaling"
]}
windows = { version = "0.62.2", features = [
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_WinRT",
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_System_WinRT_Direct3D11",
    "Graphics_Capture",
    "Graphics_DirectX_Direct3D11",
    "Graphics_Display",
    "Foundation"
]}

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-core-media = "0.3"
objc2-core-video = "0.3"
objc2-av-foundation = "0.3"
objc2-screen-capture-kit = "0.3"
block2 = "0.6"